Team-SilverTown/Team-SilverTown-MasilGasil-FE

src/app/log/record/LogRecord.controller.tsx
src/app/log/record/LogRecord.model.ts
src/app/log/record/LogRecord.styles.ts
src/app/log/record/LogRecord.view.tsx
src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
src/components/MasilMap/MasilMap.style.module.css
src/components/MasilMap/MasilMap.tsx
src/components/MasilMap/MasilMap.types.ts
src/components/MasilMap/components/CenterMarker/CenterMarker.styles.ts
src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
src/components/MasilMap/components/CustomPin/CustomPin.styles.ts
src/components/MasilMap/components/CustomPin/CustomPin.tsx
src/components/MasilMap/components/PathLine/PathLine.tsx
src/types/OriginDataType/GeoJSON.ts
src/types/OriginDataType/Pin.ts

- #13 
close #13 
- Masil Map 을 공용 컴포넌트로 제작 하였습니다.
- 핀 마커를 구현
- 경로 라인을 구현
- 중앙 마커를 구현
- 이전 #12 에 달아 주셨던 JSDOC 관련 리뷰를 해당 PR 에서 반영했습니다
- Masil Map 에 대한 JSDOC 추가와 여러 기능에서 JSDOC 을 추가했습니다 ( MAP 이 이번 프로젝트 주요 기능이라고 판단되어서 Map 컴포넌트만 상세하게 추가했습니다. )
- 핀 디자인과 중앙 마커의 디자인을 확정하면 좋을것 같습니돵
-

[ Feat ] Masil Map 구현

---

src/components/LogSimpleCard/LogSimpleCard.style.ts
src/components/LogSimpleCard/index.tsx

- #20 
- LogSimpleCard 컴포넌트 구현 했습니다.
- SimpleCard 클릭 시 일어나는 이벤트를 받아서 실행 시키도록 구현 했습니다.
- 
- **figma 디자인 사이즈대**로 만들어봤는데, **글자 크기가 너무 작은 것 같아서 전체적인 사이즈를 키우거나 레이아웃 배치를 조금 변경해도 괜찮을 것 같습니다.**
- `onClick` 같은 이벤트를 전달하는 쪽에서 `event.stopPropagation()` 함수를 사용하도록 하는 것이 좋을까요 아니면 공용 컴포넌트 내에서 처리해 주는 것이 좋을까요?? (이벤트 전파를 막는 게 좋을 것 같긴 한데.. 굳이 상관없을까요??)
- 혹시 빠진 부분이 있다면 바로 수정하도록 하겠습니다. (storybook은 원주님 PR 합쳐지면 적용해 놓겠습니다 !)
- 지역명 `max-width` 값 설정하여 길어지면 ... 처리되도록 style 추가했습니다. (추후 공용 컴포넌트에 `EllipsisText` 만들고 수정해놓겠습니다 !)
- 카드 크기 및 폰트 사이즈  늘렸습니다.
- `simplelog-Info` 섹션 Styled-Components로 분리했습니다. (LogSimpleCardInfo)

[✨Feature] LogSimpleCard 컴포넌트 생성 /#20

---

src/components/Button/Button.styles.ts

- Button, slide Button text Color 변경된 theme 에 맞게 수정
- 
- theme 색상 수정 반영
- 
- 
-

[Style] Component style fix

---

src/components/Tab/Tab.styles.ts
src/components/Tab/Tab.tsx
src/components/Tab/index.ts
src/components/index.ts
src/stories/Tab.stories.tsx

- #71 
- Tab 뷰를 제어할 수 있는 Tab 컴포넌트를 구현했습니다.
- Step Layout 과 함께 사용하는 예시는 StepLayout PR 에 작성하도록 하겠습니다!
https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/42432063/5c626a83-193a-49ef-999b-9783219ac54a
- 
- 
-

[Feat] Tab 컴포넌트 구현

---

src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
src/components/Input/Input.tsx
src/components/Textarea/Textarea.styles.ts
src/components/Textarea/Textarea.tsx
src/components/Textarea/index.ts
src/components/index.ts
src/components/modalViews/PinEditModal/PinEditModal.tsx
src/stories/Textarea.stories.tsx

- #86 
close #86 
- textarea를 공용 컴포넌트로 제작
- LogRecord 에서 textarea 적용

[Feat] Textarea 공용 컴포넌트 제작

---

package.json
src/app/explore/Explore.controller.tsx
src/app/explore/Explore.view.tsx
src/app/explore/page.tsx
src/app/explore/sections/BottomSheetSection.tsx
src/app/explore/sections/MapSection.tsx
src/components/BottomSheet/SheetBackdrop.tsx
src/components/BottomSheet/SheetContainer.tsx
src/components/BottomSheet/SheetContent.tsx
src/components/BottomSheet/SheetHeader.tsx
src/components/BottomSheet/SheetScroller.tsx
src/components/BottomSheet/constants.ts
src/components/BottomSheet/context.tsx
src/components/BottomSheet/hooks.tsx
src/components/BottomSheet/index.tsx
src/components/BottomSheet/sheet.tsx
src/components/BottomSheet/styles.ts
src/components/BottomSheet/types.tsx
src/components/BottomSheet/use-prevent-scroll.ts
src/components/BottomSheet/utils.ts
src/styles/theme.ts
yarn.lock

- #105 
https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/42432063/cf682461-abd2-4bd5-8ea6-d142f5fb7c86
-  React-modal-sheet 라이브러리 기반 bottom-sheet 구현
해당 라이브러리에는 고정된 높이 (fixedHeight) 기능을 제공하지 않습니다.
이를 해결하기 위해 해당 라이브러리 소스코드에 일부 코드를 추가하는 형식으로 해결했습니다.
fixedHeigth 를 주게되면 해당 (px, %) 높이로 초기에 렌더링 되며, 해당 높이 이하로 내려가지 않도록 합니다.
- 
- 
-

[Feat] Explore layout 구현

---

src/app/explore/components/SearchBar/SearchBar.tsx

- #104 
- 서브 브렌치 병합 간에 onValid, onInvalid 에 대한 수정이 반영 되지 않은 부분 수정
- 
- 
-

[Fix] Explore Page 오탈자

---

src/components/LoadingSpinner/LoadingSpinner.tsx
src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.tsx
src/lib/api/clientRootAPI.ts
src/lib/api/serverRootAPI.ts

- #24 
- client : PUT, DELET 핸들러 추가
- 
- 서버쪽 핸들러 구현은 길이 잘 안보이네요... 계속 API 붙여보면서 점진적으로 개선해야할 것 같습니다 .
- 급할것 같은 부분 먼저 추가해서 올립니다..!
-

[Refactor] API 핸들러 CRUD 메소드 추가

---

src/app/home/Home.constants.ts
src/app/home/Home.controller.tsx
src/app/home/Home.types.ts
src/app/home/Home.view.tsx
src/app/home/components/MyWalkRecord/MyWalkRecord.tsx
src/app/home/components/WalkList/WalkList.tsx
src/components/LogDetailCard/LogDetailCard.tsx
src/utils/calculateWalkingCalories.ts

- LogDetailCard 컴포넌트 변경
- HomePage에 사용되는 타입 구조 변경
- #117 
- HomePage의 LogDetailCard 및 함수들의 DummyData 로직 변경으로 인해 오류가 발생하여 `/home/` 접속이 되지 않아 변경된 데이터로 수정하였습니다.
- 
- 
-

[Fix] HomePage 긴급 수정

---

src/app/api/auth/[...nextauth]/options.ts
src/app/explore/sections/BottomSheetSection/BottomSheetSection.tsx
src/app/explore/sections/MapSection/MapSection.tsx
src/styles/GlobalStyle.tsx

- #201 
- 모바일 환경에서 Map 을 이동시 watch position 으로 인해 사용자의 위치로 되돌아오는 문제 해결
- 
- 
-

[Fix]  Explore Map center 에러 해결

---

src/app/log/record/context/LogRecordContext.tsx
src/app/log/record/context/reducer/LogRecordReducer.ts

Min : 25
Max : 60
time : 3s
- 
- 
-

[ Fix ] GPS 거리값 수정

---

src/app/diary/[id]/MasilDiary.view.tsx
src/app/diary/[id]/page.tsx
src/app/home/page.tsx
src/app/not-found.tsx
src/app/user/[id]/page.tsx
src/components/skeletons.tsx
tailwind.config.ts

- #209
https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/42432063/5a51cb63-6040-4edc-b87d-e8460c2b1072
- Bottom Nav 에 해당하는 메인 페이지들의 마운트 과정에 대한 스켈레톤 UI 적용 입니다.
- NexJS 의 dynamic 를 사용하여 해당 컴포넌트가 마운트 되는 과정 동안 Skeleton 컴포넌트를 대신 보여주는 형태 입니다.
- 이외 세부 페이지들은 다음의 지칭 사항을 참고하여 별도로 스켈레톤을 적용해주면 됩니다.
- query ->  isLoading 상태등을 이용하여,
- 서버사이드 컴포넌트 -> 패칭이 이루어지는 컴포넌트 상위에서 Suspens 를 사용하여, (NextJS streaming 참고) 
- 
-

[Feat] Skeleton UI 기초 적용

---

src/app/log/[id]/components/LogPin/LogPin.tsx
src/app/post/[id]/components/PostPin/PostPin.tsx
src/components/Button/Button.tsx
src/components/DotIndicator/DotIndicator.tsx
src/components/OrderTab/OrderTab.tsx

- #216 
- afterslide -> beforeSlide 로 해결
- 
- 
-

[Fix] Carousel bug fix

---

src/app/explore/Explore.controller.tsx
src/app/explore/Explore.model.tsx
src/app/explore/components/SearchBar/SearchBar.tsx
src/app/explore/sections/ListSection/ListSection.tsx
src/app/explore/sections/MapSection/MapSection.tsx
src/app/post/create/PostCreate.styles.ts
src/app/post/create/components/PostPinEdit/PostPinEdit.view.tsx
src/app/post/create/components/PostTextEdit/PostTextEdit.view.tsx
src/app/user/[id]/setting/edit/UserEdit.styles.ts
src/app/user/[id]/setting/edit/UserEdit.view.tsx
src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
src/components/UserIntensityItem/UserIntensityItem.styles.ts
src/components/UserIntensityItem/UserIntensityItem.tsx
src/lib/api/Post/client.ts
src/middleware.ts
src/styles/theme.ts
src/types/Request/Post.ts

- #222 
- 리스트 데이터 내 키워드 필터링
- curosr
- state 전파 문제로 인해 controller 로 통합
- MiddleWare 로그인 상태인 경우 setting 페이지 접근 블로킹
- 
-

[Refactor] Explore List Refactor

---

src/app/api/auth/[...nextauth]/options.ts
src/lib/AuthLoader.tsx
src/lib/api/User/server.ts
src/lib/api/serverRootAPI.ts
src/middleware.ts

- #248 
- 이슈링크의 내용을 참고해주십시오
- 
- 
-

[Fix] auth service token 에러 픽스

---

src/app/home/Home.styles.ts
src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.tsx
src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
src/components/LogDetailCard/LogDetailCard.style.ts
src/components/LogDetailCard/LogDetailCard.tsx
src/components/skeletons.tsx

- #252 
https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/114329713/41cab10f-710e-4b2a-a815-82fe6c3eb219
- HomePage 더 보기 아이콘을 더보기 텍스트로 수정
- HomePage 상단 Nav 수정 (높이가 이상함)
- LogDetailCard 컴포넌트 레이아웃 변경
- 산책로 위치 정보 추가 (PostResponse의 address 그대로 넘겨주시면 됩니다.)
- HomePage에서 좋아요 보이도록 수정
- 
-
-

[Refactor] Home Page 및 LogDetailCard 컴포넌트 수정

---

src/app/post/[id]/Post.controller.tsx
src/app/post/[id]/Post.styles.ts
src/app/post/[id]/Post.view.tsx
src/app/post/[id]/components/PostKebabMenu/PostKebabMenu.tsx
src/app/post/[id]/components/PostMemo/PostMemo.styles.ts
src/app/post/[id]/components/PostMemo/PostMemo.tsx
src/app/post/[id]/components/PostPin/PostPin.styles.ts
src/app/post/[id]/components/PostPin/PostPin.tsx
src/components/PinDetailCard/PinDetailCard.styles.ts
src/components/PinDetailCard/PinDetailCard.tsx

- #246
- 메모, 메이트 탭 콘텐츠 높이에 따라 스크롤 가능하도록 `overflow: auto` 속성 추가하였고, 핀 탭의 경우 `overflow: visible`로 default 값 지정하였습니다.
- 모바일 `width: 380px` 이하에 대한 `max-height` 지정하여 se에서도 잘리지 않도록 수정했습니다. (배포 후 정확한 체크해 보겠습니다.)
- 산책 리스트에 Pin이 담겨 있지 않을 때 Error 나타나는 부분 수정했습니다.
- 산책 리스트에 Pin이 없는 경우 Pin으로 이동 못하는 로직을 `controller`에서 처리했습니다.
- 전체적으로 임의로 padding 값을 주어 버튼 밑으로 콘텐츠가 가려지는 증상 수정했습니다. 
- 전체적으로 LogViewPage와 비슷한 로직이라 한쪽만 리뷰해 주셔도 좋을 것 같습니다.
- `dropDownMenu` 설정, 수정에 대한 알림 추가했습니다.
- 
- 프로필 이미지 사용자 프로필 이미지 나오도록 수정 완료했습니다.
- Pin 캐러셀 중 Pin을 클릭하면 모달이 나오도록 수정했습니다. (자세히 볼 수 있도록 수정)
- 핀 탭에 대한 정보가 없어도 핀 탭에 들어갈 수 있도록 수정했습니다.
- 핀 리스트가 없는 경우 `등록한 핀이 없습니다.` 라는 문구가 나타나도록 수정했습니다.

[Fix] PostView 페이지 오류 수정

---

src/app/explore/Explore.controller.tsx
src/app/explore/sections/ListSection/ListSection.tsx
src/app/home/Home.styles.ts
src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.tsx
src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
src/app/more/MoreList.constants.ts
src/app/more/MoreList.controller.tsx
src/app/more/MoreList.view.tsx
src/app/more/page.tsx
src/app/user/[id]/page.tsx
src/components/skeletons.tsx
src/lib/api/Post/client.ts
src/types/Request/Post.ts

- #253 
- infiniteLoader 가 fetch 가능한 page 를 모두 호출하는 문제 해결
- url param 으로부터 받은 정보를 토대로 fetch param 조절
- PostList api 가변 endpoint 적용
- Home 페이지 -> 전국 인기 산책로, 우리동네 인기 산책로에 대한 더보기만 가능한 상태입니다.
__
- 스켈레톤 일부 수정
- 마이페이지 -> 내가 좋아하는 산책로, 내가 작성한 산책로는 API 확인 후 추가 작업 예정입니다.
-

[Refactor] more page api 연결

---

src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx

[Fix] 더보기 버튼 처리 수정

---

src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
src/components/PinDetailCard/PinDetailCard.tsx

- merge를 dev로 잘못하여 발생한 에러를 수정했습니다. 에러가 아닌 휴먼에 에러라서 수정한 컴포넌트 prop 속성만 선택적으로 수정하였습니다.
- 다른 부분 체크하다 보니 Home 더 보기 버튼이 다시 예전 버튼으로 되돌아와 있어 마이페이지 더 보기와 동일하게 수정했습니다.
- 
- 
-

[Fix] PinDetailCard 수정으로 발생한 오류 수정

---

src/app/explore/Explore.controller.tsx
src/app/explore/sections/ListSection/ListSection.tsx
src/app/home/Home.constants.ts
src/app/more/MoreList.controller.tsx
src/app/more/MoreList.view.tsx
src/app/more/SortTab/SortTab.tsx
src/app/more/page.tsx
src/app/user/[id]/MyPage.controller.tsx
src/app/user/[id]/components/MyRecordList/MyRecordList.tsx
src/lib/api/Post/client.ts
src/types/Request/Post.ts
tailwind.config.ts

- #265 
- 내가 작성한/타유저가 작성한 산책로 목록에 대한 더보기 API 핸들링 추가 입니다.
- 
- 
-

[ Refactor ] morepage api v2

---

src/app/home/Home.styles.ts
src/app/home/Home.view.tsx
src/app/home/components/MyInfo/MyInfo.styles.ts
src/app/home/components/MyInfo/MyInfo.tsx
src/app/home/components/MyWalkRecord/MyWalkRecord.module.css
src/app/home/components/WalkStartButton/WalkStartButton.tsx
tailwind.config.ts

- #262 
https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-FE/assets/114329713/5389ef90-476c-4f73-87fa-0d9c68e007bc
- 홈페이지 Top Nav 상단에 `마실가실` 로고 추가했습니다.
- 홈페이지 Top Nav 상단 알림 아이콘 제거했습니다.
- 나의 산책 기록은 상단에 고정되고 산책 리스트만 스크롤 되도록 수정했습니다.
- 나의 산책 기록을 산책 일지 기록과 동일한 폰트 크기, 간격 색상 맞췄습니다. (타이틀 하단 간격의 경우는 가운데 정렬이기 때문에 맞출 더 여유 있게 설정했습니다.)
- 
- 상단 로고가 조금 어정쩡한 것 같은데 좋은 디자인 있을까요 ?? 
-

[Refactor] HomePage 추가 수정

---

src/app/home/components/MyLocationWeather/MyLocationWeather.tsx

- 미세먼지 데이터 중 NaN 이라는 값이 넘어와서 해당 값에 대한 예외 처리 추가 했습니다.
- 
- 
-

[hotfix] Home 페이지 미세먼지 데이터에 대한 예외 처리 추가

---

src/app/explore/sections/ListSection/ListSection.tsx
src/app/more/MoreList.view.tsx

- #285
- useCallback hook 호출 위치를 분기문 내에 위치한 룰 위반 수정
- 
- 
-

🐛fix: useCallback hook rule 위반

---

src/app/mate/create/MateCreate.constants.ts
src/app/mate/create/MateCreate.controller.tsx
src/app/mate/create/MateCreate.model.tsx
src/app/mate/create/MateCreate.styles.ts
src/app/mate/create/MateCreate.view.tsx
src/app/mate/create/components/CalendarDatePicker/CalendarDatePicker.styles.tsx
src/app/mate/create/components/OptionTimePicker/OptionTimePicker.styles.ts
src/app/mate/create/error.tsx
src/app/mate/create/page.tsx
src/components/modalViews/DoneModal/DoneModal.styles.ts
src/lib/api/Mate/client.ts
src/lib/api/endPoints.ts
src/lib/api/queryKeys.ts
src/types/Request/Mate.ts
src/types/Request/index.ts

- #204
- Mate Create API 연결
- 
- 
-

[Feat] Mate Create API 연결

---

next.config.mjs
src/app/(main)/components/AuthButton.tsx
src/app/api/auth/[...nextauth]/options.ts
src/app/auth/kakao/Kakao.tsx
src/components/LoadingSpinner/LoadingSpinner.tsx
src/components/Modal/Modal.tsx

- #296 
- popstate 발생시 모달, 로딩스피너가 유지되는 현상 수정
- 모달의 경우 뒤로가기시 모달만 닫히도록 구현하려 했으나, 히스토리에 동일한 페이지가 계속 쌓이는 문제로 인해, 닫히도록 구현
- 
- 
-

[Refactor] modal, loadingspinner close 

---

src/middleware.ts

- Resolves #318 
- 이슈에 상세하게 써봤습니다
- 쿠키 보안 설정 추가
- 
- https 통신의 배포 환경에서 테스트 필요
-

🐛fix: 리디렉션 버그 수정

---

next.config.mjs
src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx

- #334 
close #334  
비로그인 유저에대해 기존 메이트 버튼을 로그인 버튼으로 제공하였습니다.
버튼 클릭시 루트페이지로 이동
- 
-

[ Refactoring ] 메이트 페이지 로그인버튼 추가

---

src/app/home/components/StatisticContainer/StatisticContainer.tsx

- `totalCount`, `totalDistance` 파람 위치 변경

[ Fix ] 잘못된 통계 데이터 수정
